[package]
name = "inventory-tauri"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
license = ""
repository = ""
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0-rc.13", features = [] }

[dependencies]
tauri = { version = "2.0.0-rc.13", features = ["tray-icon"] }

# All necessary plugins are listed separately.
tauri-plugin-dialog = "2.0.0-rc.8"
tauri-plugin-fs = "2.0.0-rc.8"
tauri-plugin-shell = "2.0.0-rc.8"

# Your other dependencies
tauri-plugin-opener = "2.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
diesel = { version = "2.1", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = "2.1"
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "8"
bcrypt = "0.14"
thiserror = "1.0"

[features]
custom-protocol = ["tauri/custom-protocol"]
