[package]
name = "inventory-tauri"
version = "0.1.0"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "inventory_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.0.0-rc.13" }

[dependencies]
# The "dialog-all" feature has been removed from here
tauri = { version = "2.0.0-rc.13", features = ["shell-open"] }

# Add the dialog plugin with its feature
tauri-plugin-dialog = "2.0.0-rc.8"

# Your other dependencies remain the same
tauri-plugin-opener = "2.2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
diesel = { version = "2.1", features = ["sqlite", "r2d2", "chrono"] }
diesel_migrations = "2.1"
chrono = { version = "0.4", features = ["serde"] }
jsonwebtoken = "8"
bcrypt = "0.14"
thiserror = "1.0"
tokio = { version = "1.36", features = ["full"] }
libsqlite3-sys = { version = "0.27.0", features = ["bundled"] }
rand = "0.8"